name: Build RSS

on:
  schedule:
    - cron: "0 */2 * * *"   # every 2 hours
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps chromium

      - name: Build RSS
        run: npm run build

      - name: Commit and push if changed
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs/feed.xml'
          message: 'Update RSS'
          default_author: github_actions

  pages:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
      - uses: actions/deploy-pages@v4
