jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - region: default

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Install Playwright (Chromium + deps)
        run: npx playwright install --with-deps chromium
      - name: Show goto line we will run
        run: |
          echo "==== index.mjs header ===="
          head -n 20 index.mjs
          echo "==== grep goto ===="
          grep -n "page.goto" index.mjs || true
      - name: Build RSS
        run: npm run build
